import {useEffect,useMemo,useRef,useState} from 'react';
import {combineConstraints,partition} from './geometry';
import {pois,provenance,SF_BOUNDS} from './data';
import {QUESTION_DEFINITIONS} from './questions';
import {decodeState,encodeState} from './share';
import type {Constraint,QuestionKind,SharedState} from './types';
import './style.css';
const initial:SharedState={version:1,constraints:[],layers:{museum:true,library:false},viewport:{center:{lat:37.77,lng:-122.44},zoom:12}};
const colors=['#553c9a','#007c78','#b45309','#be185d','#166534'];
export default function App(){
 const mapNode=useRef<HTMLDivElement>(null),mapRef=useRef<google.maps.Map|null>(null),drawn=useRef<google.maps.Data|null>(null);
 const [state,setState]=useState<SharedState>(()=>{try{const s=new URLSearchParams(location.search).get('config');return s?decodeState(s):initial}catch{return initial}});
 const [status,setStatus]=useState<'loading'|'ready'|'error'>('loading'); const [message,setMessage]=useState('');
 const regions=useMemo(()=>({...partition('museum'),...partition('library')}),[]);const feasible=useMemo(()=>combineConstraints(state.constraints,regions),[state.constraints,regions]);
 useEffect(()=>{const key=import.meta.env.VITE_GOOGLE_MAPS_API_KEY;if(!key){setStatus('error');setMessage('Add VITE_GOOGLE_MAPS_API_KEY to .env to load the map.');return}const script=document.createElement('script');script.src=`https://maps.googleapis.com/maps/api/js?key=${encodeURIComponent(key)}&v=weekly`;script.async=true;script.onload=()=>{if(!mapNode.current)return;const map=new google.maps.Map(mapNode.current,{center:state.viewport.center,zoom:state.viewport.zoom,restriction:{latLngBounds:SF_BOUNDS,strictBounds:false},mapTypeControl:false});mapRef.current=map;setStatus('ready');map.addListener('idle',()=>{const c=map.getCenter();if(c)setState(s=>({...s,viewport:{center:{lat:c.lat(),lng:c.lng()},zoom:map.getZoom()??12}}))})};script.onerror=()=>{setStatus('error');setMessage('Google Maps could not load. Check the API key and network connection.')};document.head.append(script);return()=>script.remove()},[]);
 useEffect(()=>{const map=mapRef.current;if(!map)return;drawn.current?.setMap(null);const data=new google.maps.Data({map});drawn.current=data;Object.entries(state.layers).filter(([,on])=>on).forEach(([cat])=>Object.entries(partition(cat as 'museum'|'library')).forEach(([id,f],i)=>data.addGeoJson({...f,properties:{kind:'region',color:colors[i%colors.length],id}})));data.addGeoJson({...feasible,properties:{kind:'feasible'}});data.setStyle(f=>f.getProperty('kind')==='feasible'?{fillColor:'#16a34a',fillOpacity:.28,strokeColor:'#166534',strokeWeight:3}:{fillColor:f.getProperty('color'),fillOpacity:.12,strokeColor:f.getProperty('color'),strokeWeight:1})},[feasible,state.layers]);
 const add=()=>{const kind=(document.querySelector('#kind') as HTMLSelectElement).value as QuestionKind;setState(s=>({...s,constraints:[...s.constraints,{id:crypto.randomUUID(),name:QUESTION_DEFINITIONS[kind].label,kind,enabled:true,answer:kind==='thermometer'?'colder':'yes',origin:s.viewport.center,target:{lat:37.7857,lng:-122.4011},distanceMiles:kind==='thermometer'?5:1,direction:'north',regionId:Object.keys(regions)[0]}]}))};
 const patch=(id:string,p:Partial<Constraint>)=>setState(s=>({...s,constraints:s.constraints.map(c=>c.id===id?{...c,...p}:c)}));
 const share=async()=>{const u=new URL(location.href);u.searchParams.set('config',encodeState(state));history.replaceState({},'',u);await navigator.clipboard?.writeText(u.href);setMessage('Share URL copied and placed in the address bar.')};
 return <main><header><div><h1>SF Hiding Area</h1><p>Combine geographic answers without clipping to the coastline.</p></div><button onClick={share} aria-label="Copy shareable configuration URL">Share</button></header><div className="layout"><aside aria-label="Question constraint controls"><section><h2>Layers</h2>{(['museum','library'] as const).map(cat=><label className="toggle" key={cat}><input type="checkbox" checked={!!state.layers[cat]} onChange={e=>setState(s=>({...s,layers:{...s.layers,[cat]:e.target.checked}}))}/>{cat[0].toUpperCase()+cat.slice(1)} partitions</label>)}</section><section><h2>Questions</h2><div className="add"><select id="kind" aria-label="Question type">{Object.entries(QUESTION_DEFINITIONS).map(([k,d])=><option key={k} value={k}>{d.label}</option>)}</select><button onClick={add}>Add</button></div>{state.constraints.length===0&&<p className="muted">Add an answer to narrow the feasible area.</p>}{state.constraints.map(c=><article key={c.id}><input aria-label="Constraint name" value={c.name} onChange={e=>patch(c.id,{name:e.target.value})}/><label><input type="checkbox" checked={c.enabled} onChange={e=>patch(c.id,{enabled:e.target.checked})}/> Enabled</label>{c.kind!=='direction'&&c.kind!=='matching-region'&&<label>Miles <input aria-label={`${c.name} distance in miles`} type="number" min="0.1" step="0.1" value={c.distanceMiles} onChange={e=>patch(c.id,{distanceMiles:Number(e.target.value)})}/></label>}<button className="danger" onClick={()=>setState(s=>({...s,constraints:s.constraints.filter(x=>x.id!==c.id)}))}>Remove</button></article>)}</section><section><h2>Legend</h2>{(['museum','library'] as const).filter(c=>state.layers[c]).flatMap(cat=>pois.filter(p=>p.category===cat).map((p,i)=><div className="legend" key={p.id}><i style={{background:colors[i%colors.length]}}/>{p.name} <small>row {p.sourceRow}</small></div>))}<p className="source">Source: <a href={provenance.sourceUrl}>SF spreadsheet</a> · retrieved {provenance.retrieved}</p></section></aside><section className="map-wrap" aria-label="San Francisco feasible area map">{status!=='ready'&&<div className={`notice ${status}`} role="status">{status==='loading'?'Loading map…':message}</div>}<div ref={mapNode} className="map"/><div className="attribution">POIs: linked SF dataset · Basemap © Google</div></section></div>{message&&status==='ready'&&<div className="toast" role="status">{message}</div>}</main>
}
